# Display

This part of the book discusses the principles and practical implementations of display systems.
Fundamentally, displays convert electrical signals, i.e., image pixels, into optical signals, i.e., light emitted from the display.
Ultimately, the goal of this conversion is to present information to humans as if humans were directly looking at a real-world scene.
The scene could actually exist in the real world, or could be a virtual environment and simulated/rendered by a rendering system.
Either way, the intended scene information is encoded as a set of images, which are then turned into light by the display system.
The quality of a display system is, thus, assessed by how closely matched is the viewing experience on the display vs. that of the intended, real-world scene.

I keep using the word "display system" rather than simply "display"; this is to emphasize that a display is a system, including not only the actual devices that emit light (Chapter @sec-disp-optics) but also the electrical driving circuits (Chapter @sec-disp-elec) that use image pixels to drive the emissive devices as well as the display signal processing pipeline (Chapter @sec-disp-sp) that generates the pixel values sent to the driving circuits.
